### ISSUE TITLE
[BUG] cannot use built-in file system persistent volumes with crc due to "permission denied"

### ISSUE THREAD

**Issue by nddipiazza** [code-ready/crc#1203]
### General information

  * OS and hypervisor: I tried Windows+Hyper-V and Linux+KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```bash
crc version: 1.9.0+a68b5e0
OpenShift version: 4.3.10 (embedded in binary)
```
  
## CRC status
```bash
CRC VM:          Running
OpenShift:       Running (v4.3.10)
Disk Usage:      13.32GB of 32.72GB (Inside the CRC VM)
Cache Usage:     14.27GB
Cache Directory: C:\Users\nicho\.crc\cache```

## CRC config
```bash
empty
```

## Host Operating System
```bash
Host Name:                 DESKTOP-BIVBF6C
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          nicholas.dipiazza@gmail.com
Registered Organization:
Product ID:                00330-52212-59214-AAOEM
Original Install Date:     3/20/2020, 8:03:44 PM
System Boot Time:          4/30/2020, 4:45:30 PM
System Manufacturer:       LENOVO
System Model:              20NF0018US
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 24 Stepping 1 AuthenticAMD ~2300 Mhz
BIOS Version:              LENOVO R11ET25W (1.05 ), 4/4/2019
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-06:00) Central Time (US & Canada)
Total Physical Memory:     63,406 MB
Available Physical Memory: 46,936 MB
Virtual Memory: Max Size:  72,622 MB
Virtual Memory: Available: 54,880 MB
Virtual Memory: In Use:    17,742 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-BIVBF6C
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB4534132
                           [02]: KB4513661
                           [03]: KB4516115
                           [04]: KB4517245
                           [05]: KB4528759
                           [06]: KB4537759
                           [07]: KB4541338
                           [08]: KB4552152
                           [09]: KB4549951
Network Card(s):           4 NIC(s) Installed.
                           [01]: Intel(R) Wireless-AC 9260 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.73
                                 [02]: fe80::3077:edca:2c27:301e
                           [02]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.205.65
                                 [02]: fe80::64ad:9f39:389:d5a
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

### Steps to reproduce

  1. `crc setup`
  2. `crc start -n '8.8.8.8'`
  3. `oc login -u kubeadmin -p YOURPASSWORD https://api.crc.testing:6443`
  4. `helm repo add lucidworks https://charts.lucidworks.com`
  5. `helm install zk https://charts.lucidworks.com/zookeeper-2.1.4.tgz`
  6. check the logs of the zookeeper pod created. It will have errors.

First here is the oc describe:

```
Name:               f5-zk-zookeeper-0
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               crc-bq5fv-master-0/192.168.205.69
Start Time:         Thu, 30 Apr 2020 16:59:24 -0500
Labels:             app=zookeeper
                    component=server
                    controller-revision-hash=f5-zk-zookeeper-6877bf4789
                    release=f5-zk
                    statefulset.kubernetes.io/pod-name=f5-zk-zookeeper-0
Annotations:        k8s.v1.cni.cncf.io/networks-status=[{
    "name": "openshift-sdn",
    "interface": "eth0",
    "ips": [
        "10.128.0.49"
    ],
    "dns": {},
    "default-route": [
        "10.128.0.1"
    ]
}...
Status:         Running
IP:             10.128.0.49
Controlled By:  StatefulSet/f5-zk-zookeeper
Containers:
  zookeeper:
    Container ID:  cri-o://99aa6ade41bdce5d4c959a4154b477387e2d9234d241823057d1f247084b51e0
    Image:         zookeeper:3.5.6
    Image ID:      docker.io/library/zookeeper@sha256:2afb57a028658d84efd47e1de32d86421abe7bc5a735317a0ec8ee98b6dc2c94
    Ports:         2181/TCP, 3888/TCP, 2888/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/bash
      -xec
      /config-scripts/run
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 30 Apr 2020 17:05:40 -0500
      Finished:     Thu, 30 Apr 2020 17:05:41 -0500
    Ready:          False
    Restart Count:  6
    Liveness:       exec [sh /config-scripts/ok] delay=20s timeout=5s period=30s #success=1 #failure=2
    Readiness:      exec [sh /config-scripts/ready] delay=20s timeout=5s period=30s #success=1 #failure=2
    Environment:
      ZK_REPLICAS:                    3
      JMXAUTH:                        false
      JMXDISABLE:                     false
      JMXPORT:                        1099
      JMXSSL:                         false
      ZK_SYNC_LIMIT:                  10
      ZK_TICK_TIME:                   2000
      ZOO_AUTOPURGE_PURGEINTERVAL:    0
      ZOO_AUTOPURGE_SNAPRETAINCOUNT:  3
      ZOO_INIT_LIMIT:                 5
      ZOO_MAX_CLIENT_CNXNS:           60
      ZOO_PORT:                       2181
      ZOO_STANDALONE_ENABLED:         false
      ZOO_TICK_TIME:                  2000
    Mounts:
      /config-scripts from config (rw)
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zhcnt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-f5-zk-zookeeper-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      f5-zk-zookeeper
    Optional:  false
  default-token-zhcnt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zhcnt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age               From                         Message
  ----     ------            ----              ----                         -------
  Warning  FailedScheduling  <unknown>         default-scheduler            pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  <unknown>         default-scheduler            pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         <unknown>         default-scheduler            Successfully assigned default/f5-zk-zookeeper-0 to crc-bq5fv-master-0
  Normal   Pulling           9m                kubelet, crc-bq5fv-master-0  Pulling image "zookeeper:3.5.6"
  Normal   Pulled            9m                kubelet, crc-bq5fv-master-0  Successfully pulled image "zookeeper:3.5.6"
  Normal   Created           7m (x5 over 9m)   kubelet, crc-bq5fv-master-0  Created container zookeeper
  Normal   Started           7m (x5 over 9m)   kubelet, crc-bq5fv-master-0  Started container zookeeper
  Normal   Pulled            7m (x4 over 9m)   kubelet, crc-bq5fv-master-0  Container image "zookeeper:3.5.6" already present on machine
  Warning  BackOff           4m (x26 over 9m)  kubelet, crc-bq5fv-master-0  Back-off restarting failed container
```

Here is the persistent volume that it wants to use:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0027
  selfLink: /api/v1/persistentvolumes/pv0027
  uid: f4d2c23e-1067-4faa-a109-526ec2767e63
  resourceVersion: '298290'
  creationTimestamp: '2020-04-16T15:16:57Z'
  labels:
    volume: pv0027
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 100Gi
  hostPath:
    path: /mnt/pv-data/pv0027
    type: ''
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: default
    name: data-f5-zk-zookeeper-0
    uid: 3da15f55-7bbe-44ef-9162-83dd94b6e841
    apiVersion: v1
    resourceVersion: '298283'
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
status:
  phase: Bound
```

### Expected
Expected to be able to use the persistent volumes with no special steps.

### Actual
I have no permissions of the persistent volumes.

I changed the command to this:

```
command:
  - /usr/bin/tail
  - -f
  - /dev/null
```

and `oc rsh f5-zk-zookeeper-0` to the container and I run:

```
ls -lta /data
```

and I get an error:

```
ls: cannot open directory '/data': Permission denied
```

### Logs

```
 oc logs f5-zk-zookeeper-0
>>
+ /config-scripts/run
mkdir: cannot create directory ‘/data’: Permission denied
/config-scripts/run: line 46: /data/myid: Permission denied
+ exec java -cp '/apache-zookeeper-3.5.6-bin/lib/*:/apache-zookeeper-3.5.6-bin/*jar:/conf:' -Xmx2G -Xms2G org.apache.zookeeper.server.quorum.QuorumPeerMain /conf/zoo.cfg
2020-04-30 22:05:41,289 [myid:] - INFO  [main:QuorumPeerConfig@133] - Reading configuration from: /conf/zoo.cfg
2020-04-30 22:05:41,306 [myid:] - INFO  [main:QuorumPeerConfig@385] - clientPortAddress is 0.0.0.0/0.0.0.0:2181
2020-04-30 22:05:41,306 [myid:] - INFO  [main:QuorumPeerConfig@389] - secureClientPort is not set
2020-04-30 22:05:41,344 [myid:] - ERROR [main:QuorumPeerMain@89] - Invalid config, exiting abnormally
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /conf/zoo.cfg
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:154)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:113)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
Caused by: java.lang.IllegalArgumentException: myid file is missing
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.checkValidity(QuorumPeerConfig.java:734)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.setupQuorumPeerConfig(QuorumPeerConfig.java:605)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:420)
        at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:150)
        ... 2 more
Invalid config, exiting abnormally
```

**Comment by cfergeau** [comment]
Could it be something similar to https://github.com/code-ready/crc/issues/814 ?

**Comment by nddipiazza** [comment]
I @cfergeau - was wondering same thing.

I added this into the statefulset.yaml:

```
      initContainers:
        - name: volume-permissions
          image: bitnami/minideb            
          imagePullPolicy: Always
          command: ["chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }}", "/data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /data
```

with values.yaml

```
    securityContext:
      enabled: true
      fsGroup: 1001
      runAsUser: 1001
```

Now it does not suffer this problem. What does that mean?

**Comment by cfergeau** [comment]
This is a known limitation of the PVs created by crc. Setting manually the permissions is the only workaround I know of at the moment, so what you suggest is probably good enough.. It may be possible instead to do a `chown` manually just once.

**Comment by nddipiazza** [comment]
Closing this, because it appears to be expected behavior.

**Comment by nddipiazza** [comment]
@cfergeau  is there a parent issue for this problem? Is there any work towards a fix for this limitation?

**Comment by nddipiazza** [comment]
and I am very interested in what you mean by:

> It may be possible instead to do a chown manually just once.

**Comment by cfergeau** [comment]
Praveen pointed me at https://docs.openshift.com/container-platform/4.3/cnv/cnv_virtual_machines/cnv_virtual_disks/cnv-configuring-local-storage-for-vms.html which may be useful in your case.

**Comment by nddipiazza** [comment]
@cfergeau that was greek to me, but I can try again to read it after I get a little smarter about this stuff. Doesn't this issue where by default you do not have access to persistent volumes a big issue? How is this not a blocker for others?

**Comment by cfergeau** [comment]
> Doesn't this issue where by default you do not have access to persistent volumes a big issue? How is this not a blocker for others?

This has come up a few times actually, so it's not just you. We are currently looking at how to improve this. I suspect the needed ownership would depend on the application you are deploying? (I'm also not familiar with this stuff! ;) Setting the permissions to 777 does not sound so great.... In short, this is a known shortcoming, but we haven't figured out yet the best way to  handle it.
