### ISSUE TITLE
[BUG] CRC fails to start with "Exception 0xc0000005 0x0 0x7ff8b0eb2fff 0x5290000 PC=0x5290000"

### ISSUE THREAD

**Issue by BrentHovan** [code-ready/crc#2221]
### General information

  * OS:                                                                Windows
  * Hypervisor:                                                    Hyper-V
  * Did you run `crc setup` before starting it?:   Yes
  * Running CRC on:                                           Laptop

## CRC version
```bash
CodeReady Containers version: 1.20.0-OKD+91e49901
OpenShift version: 4.6.0-0.okd-2020-12-12-135354 (embedded in executable)
```

## CRC status
```bash
Checking file: C:\Users\BrentHovan\.crc\machines\crc\.crc-exist
Machine 'crc' does not exist. Use 'crc start' to create it
```

## CRC config
```bash
- cpus                                  : 6
- memory                            : 11264
```

## Host Operating System
```bash
Host Name:                 DESKTOP-CGCFV58
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00330-53282-53877-AAOEM
Original Install Date:     1/13/2021, 4:14:48 PM
System Boot Time:          4/12/2021, 3:52:38 PM
System Manufacturer:       Dell Inc.
System Model:              Latitude 5510
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1803 Mhz
BIOS Version:              Dell Inc. 1.4.3, 12/23/2020
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     15,980 MB
Available Physical Memory: 4,190 MB
Virtual Memory: Max Size:  34,374 MB
Virtual Memory: Available: 15,172 MB
Virtual Memory: In Use:    19,202 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-CGCFV58
Hotfix(s):                 13 Hotfix(s) Installed.
                           [01]: KB4601554
                           [02]: KB4534170
                           [03]: KB4537759
                           [04]: KB4542335
                           [05]: KB4545706
                           [06]: KB4562830
                           [07]: KB4577266
                           [08]: KB4577586
                           [09]: KB4580325
                           [10]: KB4589212
                           [11]: KB4598481
                           [12]: KB5000802
                           [13]: KB5000858
Network Card(s):           7 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (10) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Hardware not present
                           [02]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [03]: DisplayLink Network Adapter NCM
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.254.254
                                 IP address(es)
                                 [01]: 192.168.254.29
                                 [02]: fe80::c0e4:ddc9:f320:1155
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.23.80.1
                                 [02]: fe80::e167:ed8f:c5d1:78f2
                           [05]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (WSL)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.32.1
                                 [02]: fe80::c01d:2656:46d4:d4a1
                           [06]: Microsoft Network Adapter Multiplexor Driver
                                 Connection Name: Network Bridge
                                 Status:          Media disconnected
                           [07]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (crc)
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

### Steps to reproduce

  1. Download crc.exe for windows (https://dl.fedoraproject.org/pub/alt/okd-crc/windows-amd64/crc.exe)
  2. Add crc.exe to path and run 'crc setup'
  3. Run 'crc start'
  4. (Optional) Add external virtual switch "crc" via Hyper-V Manager

### Expected

CRC to start

### Actual
```bash
>  crc start --log-level debug
DEBU CodeReady Containers version: 1.20.0-OKD+91e49901
DEBU OpenShift version: 4.6.0-0.okd-2020-12-12-135354 (embedded in executable)
DEBU Total memory of system is 16756752384 bytes
Exception 0xc0000005 0x0 0x7ff8b0eb2fff 0x5290000
PC=0x5290000

syscall.Syscall6(0x7ff8b0685b20, 0x4, 0xc0000b05a0, 0x0, 0xc00000ff30, 0xc00000fea0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/golang/src/runtime/syscall_windows.go:201 +0xfa
syscall.GetAddrInfoW(0xc0000b05a0, 0x0, 0xc00000ff30, 0xc00000fea0, 0x15, 0x0)
        /usr/lib/golang/src/syscall/zsyscall_windows.go:1718 +0xb3
net.(*Resolver).lookupIP.func1(0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/lookup_windows.go:108 +0x244
net.(*Resolver).lookupIP.func2(0xc0002ee6c0, 0xc0002ce8a0)
        /usr/lib/golang/src/net/lookup_windows.go:145 +0x32
created by net.(*Resolver).lookupIP
        /usr/lib/golang/src/net/lookup_windows.go:144 +0x400

goroutine 1 [select]:
net/http.(*Transport).getConn(0x1f02040, 0xc0001781e0, 0x0, 0x13c4359, 0x5, 0xc0002f2600, 0x18, 0x0, 0x0, 0x0, ...)
        /usr/lib/golang/src/net/http/transport.go:1234 +0x55a
net/http.(*Transport).roundTrip(0x1f02040, 0xc0002f4900, 0xc000178030, 0xc00009a8ac, 0xc00009a8a0)
        /usr/lib/golang/src/net/http/transport.go:522 +0x60a
net/http.(*Transport).RoundTrip(0x1f02040, 0xc0002f4900, 0x1f02040, 0xc015a029d9400d44, 0x12bef91c1)
        /usr/lib/golang/src/net/http/roundtrip.go:17 +0x3c
net/http.send(0xc0002f4800, 0x156e960, 0x1f02040, 0xc015a029d9400d44, 0x12bef91c1, 0x1f1c300, 0xc0000060b0, 0xc015a029d9400d44, 0x1, 0x0)
        /usr/lib/golang/src/net/http/client.go:250 +0x44a
net/http.(*Client).send(0xc000131dd0, 0xc0002f4800, 0xc015a029d9400d44, 0x12bef91c1, 0x1f1c300, 0xc0000060b0, 0x0, 0x1, 0x1330a40)
        /usr/lib/golang/src/net/http/client.go:174 +0x101
net/http.(*Client).do(0xc000131dd0, 0xc0002f4800, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:641 +0x3d5
net/http.(*Client).Do(...)
        /usr/lib/golang/src/net/http/client.go:509
net/http.(*Client).Get(0xc000131dd0, 0x13c4359, 0x52, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/http/client.go:398 +0xc2
github.com/code-ready/crc/pkg/crc/version.getCRCLatestVersionFromMirror(0x0, 0x0, 0x0)
        /crc-build/crc/pkg/crc/version/version.go:70 +0xab
github.com/code-ready/crc/pkg/crc/version.NewVersionAvailable(0xc000493c30, 0x583673, 0x113faa0, 0x1eb3d00, 0x113faa0)
        /crc-build/crc/pkg/crc/version/version.go:94 +0x2d
github.com/code-ready/crc/cmd/crc/cmd.checkIfNewVersionAvailable(0x113fa00)
        /crc-build/crc/cmd/crc/cmd/start.go:226 +0x3d
github.com/code-ready/crc/cmd/crc/cmd.runStart(0xc0002ee1a0, 0x0, 0x2, 0x0, 0x0, 0x0)
        /crc-build/crc/cmd/crc/cmd/start.go:60 +0x98
github.com/code-ready/crc/cmd/crc/cmd.glob..func12(0x1f047c0, 0xc0002ee1a0, 0x0, 0x2)
        /crc-build/crc/cmd/crc/cmd/start.go:49 +0x9e
github.com/spf13/cobra.(*Command).execute(0x1f047c0, 0xc0002ee180, 0x2, 0x2, 0x1f047c0, 0xc0002ee180)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x1f04280, 0x405b46, 0xc000080058, 0x0)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/code-ready/crc/cmd/crc/cmd.Execute()
        /crc-build/crc/cmd/crc/cmd/root.go:78 +0x34
main.main()
        /crc-build/crc/cmd/crc/main.go:8 +0x27

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/golang/src/runtime/sigqueue.go:147 +0xa3
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.init.0
        /usr/lib/golang/src/os/signal/signal_unix.go:29 +0x48

goroutine 34 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x1f1c6e0)
        /root/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:1131 +0x92
created by k8s.io/klog/v2.init.0
        /root/go/pkg/mod/k8s.io/klog/v2@v2.3.0/klog.go:416 +0xdd

goroutine 6 [select]:
net/http.setRequestCancel.func3(0x0, 0xc000178030, 0xc0000f00a0, 0xc00009a8ac, 0xc000320120)
        /usr/lib/golang/src/net/http/client.go:321 +0xd6
created by net/http.setRequestCancel
        /usr/lib/golang/src/net/http/client.go:320 +0x252

goroutine 7 [select]:
net.(*Resolver).lookupIPAddr(0x1f1a1a0, 0x1595c00, 0xc0002ce6c0, 0x135935f, 0x3, 0xc0002f2600, 0x14, 0x1bb, 0x0, 0x0, ...)
        /usr/lib/golang/src/net/lookup.go:275 +0x66b
net.(*Resolver).internetAddrList(0x1f1a1a0, 0x1595c00, 0xc0002ce6c0, 0x135935f, 0x3, 0xc0002f2600, 0x18, 0x0, 0x0, 0x0, ...)
        /usr/lib/golang/src/net/ipsock.go:280 +0x60c
net.(*Resolver).resolveAddrList(0x1f1a1a0, 0x1595c00, 0xc0002ce6c0, 0x1359cfe, 0x4, 0x135935f, 0x3, 0xc0002f2600, 0x18, 0x0, ...)
        /usr/lib/golang/src/net/dial.go:220 +0x50d
net.(*Dialer).DialContext(0xc0001040c0, 0x1595bc0, 0xc00009a128, 0x135935f, 0x3, 0xc0002f2600, 0x18, 0x0, 0x0, 0x0, ...)
        /usr/lib/golang/src/net/dial.go:402 +0x205
net/http.(*Transport).dial(0x1f02040, 0x1595bc0, 0xc00009a128, 0x135935f, 0x3, 0xc0002f2600, 0x18, 0x0, 0x0, 0x0, ...)
        /usr/lib/golang/src/net/http/transport.go:1040 +0x1fc
net/http.(*Transport).dialConn(0x1f02040, 0x1595bc0, 0xc00009a128, 0x0, 0x13c4359, 0x5, 0xc0002f2600, 0x18, 0x0, 0x0, ...)
        /usr/lib/golang/src/net/http/transport.go:1478 +0x1945
net/http.(*Transport).dialConnFor(0x1f02040, 0xc000306160)
        /usr/lib/golang/src/net/http/transport.go:1308 +0xe3
created by net/http.(*Transport).queueForDial
        /usr/lib/golang/src/net/http/transport.go:1277 +0x424

goroutine 8 [select]:
net.(*Resolver).lookupIP(0x1f1a1a0, 0x1595b80, 0xc0000c84c0, 0x135935f, 0x3, 0xc0002f2600, 0x14, 0x0, 0x0, 0x0, ...)
        /usr/lib/golang/src/net/lookup_windows.go:150 +0x1a0
net.glob..func1(0x1595b80, 0xc0000c84c0, 0xc000083360, 0x135935f, 0x3, 0xc0002f2600, 0x14, 0x0, 0x0, 0xc00000dfc0, ...)
        /usr/lib/golang/src/net/hook.go:23 +0x79
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/net/lookup.go:269 +0x133
internal/singleflight.(*Group).doCall(0x1f1a1b0, 0xc0000f0140, 0xc0002f2700, 0x18, 0xc0000c8500)
        /usr/lib/golang/src/internal/singleflight/singleflight.go:95 +0x35
created by internal/singleflight.(*Group).DoChan
        /usr/lib/golang/src/internal/singleflight/singleflight.go:88 +0x2c3
rax     0x7ff8adb10b92
rbx     0x7ff8adb10b90
rcx     0x77
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x0
rsp     0x287eac0
r8      0x97c
r9      0x97c
r10     0x97c
r11     0x97c
r12     0xc000007a
r13     0x0
r14     0x7ff8adb10b92
r15     0x7ff8b0cb0000
rip     0x5290000
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
```

### Logs
None generated

This procedure did not fix my issue:
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

**Comment by gbraad** [comment]
This is likely an issue with the OKD release. We do not maintain these releases.
Please reach out to the maintainer for a new version as 1.20 sounds old.
