### ISSUE TITLE
[BUG] Don't crash the daemon if clients send unexpected data for a request

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#2276]
The daemon crashes with the following error, if a client request `SetConfig` and has empty data:

```
PS C:\Users\Anjan\github.com\code-ready\crc> crc daemon
INFO Checking if podman remote executable is cached
INFO Checking if admin-helper executable is cached
INFO Checking minimum RAM requirements
INFO Checking if running in a shell with administrator rights
INFO Checking Windows 10 release
INFO Checking Windows edition
INFO Checking if Hyper-V is installed and operational
INFO Checking if user is a member of the Hyper-V Administrators group
INFO Checking if Hyper-V service is enabled
INFO Checking if the Hyper-V virtual switch exist
INFO Found Virtual Switch to use: Default Switch
INFO listening vsock://00000400-FACB-11E6-BD58-64006A7986D3
INFO listening \\.\pipe\crc-http
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 27 [running]:
github.com/code-ready/crc/pkg/crc/api.(*Handler).SetConfig(0xc000584ba0, 0xc00058adb0, 0x10, 0x10, 0x0, 0xc0003adf90)
        C:/Users/Anjan/github.com/code-ready/crc/pkg/crc/api/handlers.go:139 +0x717
github.com/code-ready/crc/pkg/crc/api.Server.handleRequest(0x1fb2c28, 0xc000584ba0, 0x1fa07a0, 0xc000584b70, 0xc00058ada0, 0x9, 0xc00058adb0, 0x10, 0x10, 0x1fb0f68, ...)
        C:/Users/Anjan/github.com/code-ready/crc/pkg/crc/api/api.go:65 +0x414
created by github.com/code-ready/crc/pkg/crc/api.Server.handleConnections
        C:/Users/Anjan/github.com/code-ready/crc/pkg/crc/api/api.go:94 +0x3fa
```

**Comment by guillaumerose** [comment]
It would be probably good to use a more high-level framework for the HTTP API. It would avoid this kind of problems. 

https://github.com/gin-gonic/gin, https://github.com/gorilla/mux or https://echo.labstack.com/

Personally I would like a framework that do the JSON marshalling/unmarshalling for me.
