### ISSUE TITLE
CRC crashes after successful image push with "error: You must be logged in to the server (Unauthorized)"

### ISSUE THREAD

**Issue by eltimen** [code-ready/crc#2749]
### General information

  * OS: Linux
  * Hypervisor: None
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Baremetal-Server

## CRC version
```bash
CodeReady Containers version: 1.32.1+4d40571f
OpenShift version: 4.8.5 (embedded in executable)
```
  
## CRC status
<details>

```bash
DEBU HTTP-PROXY: <proxy>, HTTPS-PROXY: <proxy>, NO-PROXY: 127.0.0.1,localhost,127.0.0.1,localhost,<internal_domain>,.testing, proxyCAFile:
DEBU CodeReady Containers version: 1.32.1+4d40571f
DEBU OpenShift version: 4.8.5 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: /home/user/.crc/machines/crc/.crc-exist
DEBU Checking file: /home/user/.crc/machines/crc/.crc-exist
DEBU Found binary path at /home/user/.crc/bin/crc-driver-libvirt
DEBU Launching plugin server for driver libvirt
DEBU Plugin server listening at address 127.0.0.1:39787
DEBU () Calling .GetVersion
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetState
DEBU (crc) DBG | time="2021-09-21T17:00:18+03:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-09-21T17:00:18+03:00" level=debug msg="Fetching VM..."
DEBU (crc) Calling .GetBundleName
DEBU (crc) Calling .GetIP
DEBU (crc) DBG | time="2021-09-21T17:00:18+03:00" level=debug msg="GetIP called for crc"
DEBU (crc) DBG | time="2021-09-21T17:00:18+03:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-09-21T17:00:18+03:00" level=debug msg="IP address: 192.168.130.11"
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [/home/user/.crc/machines/crc/id_ecdsa /home/user/.crc/cache/crc_libvirt_4.8.5/id_ecdsa_crc]
DEBU SSH command results: err: <nil>, output: 32737570816 17355423744 /sysroot
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU Successfully made call to close driver server
DEBU Making call to close connection to plugin binary
DEBU (crc) DBG | time="2021-09-21T17:00:18+03:00" level=debug msg="Closing plugin on server side"
CRC VM:          Running
OpenShift:       Running (v4.8.5)
Disk Usage:      17.36GB of 32.74GB (Inside the CRC VM)
Cache Usage:     15.96GB
Cache Directory: /home/user/.crc/cache
```
</details>

## CRC config
```bash
- consent-telemetry                     : no
- cpus                                  : 16
- http-proxy                            : <proxy>
- https-proxy                           : <proxy>
- memory                                : 51200
- no-proxy                              : 127.0.0.1,localhost,<internal_domain>,.testing
```

## Host Operating System
<details>

```bash
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
```
</details>

### Steps to reproduce

  1. Create build configuration
  ```bash
cat rhel8-runtime-2021-3-394-openshift.dockerfile | oc new-build --name rhel8-runtime-2021-3-394-openshift --dockerfile=- --build-secret entitlement --build-config-map rhsm-conf:rhsm-conf --build-config-map rhsm-ca:rhsm-ca --build-arg package_url=l_openvino_toolkit_runtime_rhel8_p_2021.3.394.tgz --build-arg INTEL_OPENCL=19.41.14441 --push-secret registry --to=<registry>/rhel8_runtime:2021.3.394_openshift --to-docker=true
```
  2. Change configuration
  ```bash
oc patch bc/rhel8-runtime-2021-3-394-openshift -p '{"spec":{"strategy":{"dockerStrategy":{"imageOptimizationPolicy":"SkipLayers"}}}}'
  ```
  3. Start build
```bash
oc start-build rhel8-runtime-2021-3-394-openshift --from-file l_openvino_toolkit_runtime_rhel8_p_2021.3.394.tgz --no-cache=true --follow --wait
```

### Expected
Push successful, exit code 0

### Actual
Periodically, OpenShift crashes with `error: You must be logged in to the server (Unauthorized)` in the log (but the image has been successfully pushed on a registry). After this, `crc status` becomes `Unreacheable` for 1 minute.
```
STEP 48: COMMIT temp.builder.openshift.io/default/rhel8-runtime-2021-3-394-openshift-2:56b37a45
Getting image source signatures
Copying blob sha256:e39c3abf0df93fca44921f3548fcf6e139afdcb2ac9b7baa6c47b39f87113b32
Copying blob sha256:8f26704f753cbe8b20afc01e97a4cb652befe26791b4d33193afc99ce544ebf5
Copying blob sha256:8a3006c25a9587654d1b93e230225d0d91c1d583c453617a6f778aa2a1ad9fe4
Copying config sha256:fd0e4df62aea40680a691fb3f1be6ae1c9393a932eba701ce0dd961e78eb7083
Writing manifest to image destination
Storing signatures
--> fd0e4df62ae
fd0e4df62aea40680a691fb3f1be6ae1c9393a932eba701ce0dd961e78eb7083

Pushing image <registry>/rhel8_runtime:2021.3.394_openshift ...
Getting image source signatures
Copying blob sha256:8a3006c25a9587654d1b93e230225d0d91c1d583c453617a6f778aa2a1ad9fe4
Copying blob sha256:296e14ee24149e14d573a1fbf5b5a625c7bb0cc22f5b2a8b180e833258187948
Copying blob sha256:356f18f3a935b2f226093720b65383048249413ed99da72c87d5be58cc46661c
Copying config sha256:fd0e4df62aea40680a691fb3f1be6ae1c9393a932eba701ce0dd961e78eb7083
Writing manifest to image destination
Storing signatures
Successfully pushed <registry>/rhel8_runtime@sha256:0a2bf3c900943e1dbaa951d66ebdf607d69cb61aa22a9e4ab09326f716b3b09d
Push successful
error: You must be logged in to the server (Unauthorized)
```
If I use build config without push settings, I often see this errors:
```
Pushing image image-registry.openshift-image-registry.svc:5000/default/rhel8-runtime-2021-3-394-openshift-2:latest ...
Getting image source signatures
Warning: Push failed, retrying in 5s ...
Getting image source signatures
Warning: Push failed, retrying in 5s ...
Getting image source signatures
Warning: Push failed, retrying in 5s ...
Registry server Address: 
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.imagestore=/var/lib/shared]image-registry.openshift-image-registry.svc:5000/default/rhel8-runtime-2021-3-394-openshift-2:latest" to "docker://image-registry.openshift-image-registry.svc:5000/default/rhel8-runtime-2021-3-394-openshift-2:latest": Error trying to reuse blob sha256:296e14ee24149e14d573a1fbf5b5a625c7bb0cc22f5b2a8b180e833258187948 at destination: unable to retrieve auth token: invalid username/password: unauthorized: unable to validate token: ServiceUnavailable
error: the build default/rhel8-runtime-2021-3-394-openshift-2-2 status is "Failed"
```

**Comment by praveenkumar** [comment]
@eltimen when `crc status` become unreachable can you provide the output of `crc status --log-level debug` is it because apiserver reconcile happen because of this push operation or something else?

**Comment by eltimen** [comment]
@praveenkumar Output after `error: You must be logged in to the server (Unauthorized)` message:
```
DEBU HTTP-PROXY: <proxy>, HTTPS-PROXY: <proxy>, NO-PROXY: 127.0.0.1,localhost,127.0.0.1,localhost,<internal_domain>,.testing, proxyCAFile:
DEBU CodeReady Containers version: 1.32.1+4d40571f
DEBU OpenShift version: 4.8.5 (embedded in executable)
DEBU Running 'crc status'
DEBU Checking file: /home/user/.crc/machines/crc/.crc-exist
DEBU Checking file: /home/user/.crc/machines/crc/.crc-exist
DEBU Found binary path at /home/user/.crc/bin/crc-driver-libvirt
DEBU Launching plugin server for driver libvirt
DEBU Plugin server listening at address 127.0.0.1:41799
DEBU () Calling .GetVersion
DEBU Using API Version 1
DEBU () Calling .SetConfigRaw
DEBU () Calling .GetMachineName
DEBU (crc) Calling .GetState
DEBU (crc) DBG | time="2021-09-22T13:58:29+03:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-09-22T13:58:29+03:00" level=debug msg="Fetching VM..."
DEBU (crc) Calling .GetBundleName
DEBU (crc) Calling .GetIP
DEBU (crc) DBG | time="2021-09-22T13:58:29+03:00" level=debug msg="GetIP called for crc"
DEBU (crc) DBG | time="2021-09-22T13:58:29+03:00" level=debug msg="Getting current state..."
DEBU (crc) DBG | time="2021-09-22T13:58:29+03:00" level=debug msg="IP address: 192.168.130.11"
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [/home/user/.crc/machines/crc/id_ecdsa /home/user/.crc/cache/crc_libvirt_4.8.5/id_ecdsa_crc]
DEBU SSH command results: err: <nil>, output: 32737570816 19654758400 /sysroot
DEBU authentication operator not available, Reason: APIServices_Error
DEBU Making call to close driver server
DEBU (crc) Calling .Close
DEBU Successfully made call to close driver server
DEBU Making call to close connection to plugin binary
DEBU (crc) DBG | time="2021-09-22T13:58:30+03:00" level=debug msg="Closing plugin on server side"
CRC VM:          Running
OpenShift:       Stopped (v4.8.5)
Disk Usage:      19.65GB of 32.74GB (Inside the CRC VM)
Cache Usage:     15.96GB
Cache Directory: /home/user/.crc/cache
```
After ~30 sec, before status changes to "Running":
```
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1
DEBU Using ssh private keys: [/home/user/.crc/machines/crc/id_ecdsa /home/user/.crc/cache/crc_libvirt_4.8.5/id_ecdsa_crc]
DEBU SSH command results: err: <nil>, output: 32737570816 19626233856 /sysroot
DEBU authentication operator not available, Reason: APIServerDeployment_NoPod::APIServices_PreconditionNotReady
```

**Comment by praveenkumar** [comment]
This looks like the issue with auth operator which reconcile, may be auth operator logs tells more around what going on or if you can provide the `rhel8-runtime-2021-3-394-openshift.dockerfile` we can try to reproduce it.

**Comment by eltimen** [comment]
@praveenkumar Could you please explain which commands I should use to get this logs?

I use this dockerfile [rhel8-runtime-2021-3-394-openshift.dockerfile.txt](https://github.com/code-ready/crc/files/7211962/rhel8-runtime-2021-3-394-openshift.dockerfile.txt).  
The required `l_openvino_toolkit_runtime_rhel8_p_2021.3.394.tgz` archive is available [here](https://storage.openvinotoolkit.org/repositories/openvino/packages/2021.3/l_openvino_toolkit_runtime_rhel8_p_2021.3.394.tgz)

**Comment by praveenkumar** [comment]
> @praveenkumar Could you please explain which commands I should use to get this logs?

@eltimen something like following should provide info regarding this failure.
```
$ oc get pods -n openshift-authentication-operator 
NAME                                       READY   STATUS    RESTARTS   AGE
authentication-operator-59c79999b9-2w8mg   1/1     Running   0          12d
$ oc logs authentication-operator-59c79999b9-2w8mg -n openshift-authentication-operator
```

And if this doesn't have info then look into the auth pods logs
```
$ oc get pods -n openshift-authentication
NAME                               READY   STATUS    RESTARTS   AGE
oauth-openshift-7f5c448f54-nbnvm   1/1     Running   0          10m
$ oc logs oauth-openshift-7f5c448f54-nbnvm -n openshift-authentication
```

**Comment by eltimen** [comment]
@praveenkumar I collected this logs immediately after failure:
[openshift-authentication-operator.txt](https://github.com/code-ready/crc/files/7215750/openshift-authentication-operator.txt)
[openshift-authentication.txt](https://github.com/code-ready/crc/files/7215752/openshift-authentication.txt)

**Comment by praveenkumar** [comment]
@eltimen we have new release which contain new version of OCP-4.8,12 and also major proxy fixes can you try that and let us know if that solve your issue?

**Comment by eltimen** [comment]
@praveenkumar I upgraded to 1.33.1 but the issue still persists

**Comment by cfergeau** [comment]
I've tried to reproduce this, but the build seems to fail earlier with a timeout. If you can still reproduce, could you run `oc start-build` with `-v10`? I wonder if this could be some components in the cluster restarting unexpectedly because of memory/cpu pressure?

**Comment by eltimen** [comment]
Hi @cfergeau,
I was able to reproduce this issue with `-v10` and collected the following logs
```
Push successful
I1210 11:08:15.299730   39311 round_trippers.go:435] curl -k -v -XGET  -H "Accept: application/json, */*" -H "Authorization: Bearer <masked>" -H "User-Agent: oc/4.8.0 (linux/amd64) kubernetes/a0c12be" 'https://api.crc.testing:6443/apis/build.openshift.io/v1/namespaces/default/builds?fieldSelector=metadata.name%3Drhel8-runtime-2022-1-openshift-2'
I1210 11:08:45.300909   39311 round_trippers.go:454] GET https://api.crc.testing:6443/apis/build.openshift.io/v1/namespaces/default/builds?fieldSelector=metadata.name%3Drhel8-runtime-2022-1-openshift-2 401 Unauthorized in 30001 milliseconds
I1210 11:08:45.300933   39311 round_trippers.go:460] Response Headers:
I1210 11:08:45.300937   39311 round_trippers.go:463]     Audit-Id: 3665e5e0-24d2-4d56-8457-22ec5eb3fb4f
I1210 11:08:45.300940   39311 round_trippers.go:463]     Cache-Control: no-cache, private
I1210 11:08:45.300942   39311 round_trippers.go:463]     Content-Type: application/json
I1210 11:08:45.300944   39311 round_trippers.go:463]     Content-Length: 129
I1210 11:08:45.300946   39311 round_trippers.go:463]     Date: Fri, 10 Dec 2021 08:08:50 GMT
I1210 11:08:45.300960   39311 request.go:1123] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
I1210 11:08:45.301223   39311 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}]
F1210 11:08:45.301242   39311 helpers.go:115] error: You must be logged in to the server (Unauthorized)
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00013e001, 0xc00091c160, 0x68, 0x141)
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x5c17580, 0xc000000003, 0x0, 0x0, 0xc000494000, 0x4a41f6c, 0xa, 0x73, 0x11e0400)
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:970 +0x191
k8s.io/klog/v2.(*loggingT).printDepth(0x5c17580, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc0010b6730, 0x1, 0x1)
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:733 +0x16f
k8s.io/klog/v2.FatalDepth(...)
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:1495
k8s.io/kubectl/pkg/cmd/util.fatal(0xc000e5c540, 0x39, 0x1)
	/go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x288
k8s.io/kubectl/pkg/cmd/util.checkErr(0x42ba760, 0xc000fee3c0, 0x3fb1878)
	/go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x935
k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
	/go/src/github.com/openshift/oc/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
github.com/openshift/oc/pkg/cli/startbuild.NewCmdStartBuild.func1(0xc0008ed400, 0xc000453570, 0x1, 0x7)
	/go/src/github.com/openshift/oc/pkg/cli/startbuild/startbuild.go:160 +0xf7
github.com/spf13/cobra.(*Command).execute(0xc0008ed400, 0xc000453490, 0x7, 0x7, 0xc0008ed400, 0xc000453490)
	/go/src/github.com/openshift/oc/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000463180, 0x2, 0xc000463180, 0x2)
	/go/src/github.com/openshift/oc/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/openshift/oc/vendor/github.com/spf13/cobra/command.go:897
main.main()
	/go/src/github.com/openshift/oc/cmd/oc/oc.go:93 +0x645

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x5c17580)
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
	/go/src/github.com/openshift/oc/vendor/k8s.io/klog/v2/klog.go:418 +0xdf

goroutine 9 [select]:
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3fb1788, 0x42baa60, 0xc000a6e000, 0x1, 0xc00010e360)
	/go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x118
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x3fb1788, 0x12a05f200, 0x0, 0xc000024001, 0xc00010e360)
	/go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/apimachinery/pkg/util/wait.Forever(0x3fb1788, 0x12a05f200)
	/go/src/github.com/openshift/oc/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
created by k8s.io/component-base/logs.InitLogs
	/go/src/github.com/openshift/oc/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a

goroutine 10 [select, 20 minutes]:
io.(*pipe).Read(0xc000f23800, 0xc000790000, 0x1000, 0x1000, 0x3875720, 0x1, 0xc000790000)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/io/pipe.go:57 +0xcb
io.(*PipeReader).Read(0xc000351800, 0xc000790000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/io/pipe.go:134 +0x4c
bufio.(*Scanner).Scan(0xc00073a180, 0x0)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/bufio/scan.go:214 +0xa9
github.com/openshift/oc/pkg/cli/admin/mustgather.newPrefixWriter.func1(0xc00073a180, 0x42bc2c0, 0xc00013e008, 0x3dfde2b, 0x17)
	/go/src/github.com/openshift/oc/pkg/cli/admin/mustgather/mustgather.go:495 +0x13e
created by github.com/openshift/oc/pkg/cli/admin/mustgather.newPrefixWriter
	/go/src/github.com/openshift/oc/pkg/cli/admin/mustgather/mustgather.go:494 +0x1d0

goroutine 100 [IO wait]:
internal/poll.runtime_pollWait(0x7f995603e3d8, 0x72, 0xffffffffffffffff)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000e83718, 0x72, 0x4600, 0x468d, 0xffffffffffffffff)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000e83700, 0xc000fc6800, 0x468d, 0x468d, 0x0, 0x0, 0x0)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000e83700, 0xc000fc6800, 0x468d, 0x468d, 0x4688, 0xc000fc6800, 0x5)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000628008, 0xc000fc6800, 0x468d, 0x468d, 0x0, 0x0, 0x0)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/net/net.go:183 +0x91
crypto/tls.(*atLeastReader).Read(0xc001020168, 0xc000fc6800, 0x468d, 0x468d, 0x4688, 0xc0000a0c00, 0x0)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/crypto/tls/conn.go:776 +0x63
bytes.(*Buffer).ReadFrom(0xc000796278, 0x42b6f80, 0xc001020168, 0x11dda45, 0x39f0e20, 0x3cfa380)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc000796000, 0x42bbde0, 0xc000628008, 0x5, 0xc000628008, 0x8a)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc000796000, 0x0, 0x0, 0x1)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc000796000, 0xc0007d0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/crypto/tls/conn.go:1276 +0x165
bufio.(*Reader).Read(0xc00039b9e0, 0xc0007c42d8, 0x9, 0x9, 0x179156b, 0xc000f97c78, 0x11d8ce5)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x42b6cc0, 0xc00039b9e0, 0xc0007c42d8, 0x9, 0x9, 0x9, 0xc0002d6870, 0x557978c168eb00, 0xc0002d6870)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/io/io.go:328 +0x87
io.ReadFull(...)
	/opt/rh/go-toolset-1.16/root/usr/lib/go-toolset-1.16-golang/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader(0xc0007c42d8, 0x9, 0x9, 0x42b6cc0, 0xc00039b9e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/oc/vendor/golang.org/x/net/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0007c42a0, 0xc000cd04e0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/oc/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000f97fa8, 0x0, 0x0)
	/go/src/github.com/openshift/oc/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000702780)
	/go/src/github.com/openshift/oc/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/go/src/github.com/openshift/oc/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5
```
