### ISSUE TITLE
[Dev] oc-env fails when podman preset in used

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#2913]
```
 crc git:(dev) crc oc-env
export PATH="/Users/prkumar/.crc/bin/oc:$PATH"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2407f2d]

goroutine 1 [running]:
github.com/code-ready/crc/pkg/crc/network.(*ProxyConfig).IsEnabled(...)
	/Users/prkumar/work/github/crc/pkg/crc/network/proxy.go:180
github.com/code-ready/crc/cmd/crc/cmd.runOcEnv(0x3bd6700, 0x0, 0x0, 0x115ac3a8, 0x1d3451c230caa)
	/Users/prkumar/work/github/crc/cmd/crc/cmd/oc_env.go:41 +0x18d
github.com/code-ready/crc/cmd/crc/cmd.glob..func6(0x365d6e0, 0x3bd6700, 0x0, 0x0, 0xc00089dd28, 0x1)
	/Users/prkumar/work/github/crc/cmd/crc/cmd/oc_env.go:20 +0x3f
github.com/code-ready/crc/cmd/crc/cmd.executeWithLogging.func1(0x365d6e0, 0x3bd6700, 0x0, 0x0, 0x0, 0x0)
	/Users/prkumar/work/github/crc/cmd/crc/cmd/root.go:170 +0x131
github.com/spf13/cobra.(*Command).execute(0x365d6e0, 0x3bd6700, 0x0, 0x0, 0x365d6e0, 0x3bd6700)
	/Users/prkumar/work/github/crc/vendor/github.com/spf13/cobra/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x365dbe0, 0xc00012e008, 0x257c820, 0x3bd6700)
	/Users/prkumar/work/github/crc/vendor/github.com/spf13/cobra/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/prkumar/work/github/crc/vendor/github.com/spf13/cobra/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/prkumar/work/github/crc/vendor/github.com/spf13/cobra/command.go:895
github.com/code-ready/crc/cmd/crc/cmd.Execute()
	/Users/prkumar/work/github/crc/cmd/crc/cmd/root.go:105 +0x117
main.main()
	/Users/prkumar/work/github/crc/cmd/crc/main.go:8 +0x25
```

**Comment by cfergeau** [comment]
This is fixed by https://github.com/code-ready/crc/commit/f99dbcb7fce121303ad9df6720c6f6077e663385
However, we can keep this open to decide what to do with `crc oc-env` when the podman preset is in use, as `oc-env` does not make a lot of sense in a podman context.
