### ISSUE TITLE
[BUG] Podman preset is broken with crc 2.4.1 and crc 2.5.0 releases

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#3235]
If one decides to use the podman bundle on linux for some reason (it's not needed as podman can be used natively on linux):
```
$ crc config set preset podman
$ crc start
[...]
INFO Adding new bearer token for cockpit webconsole                                               
failed to add podman system connection exit status 2: fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]                                 
                
runtime stack:                                                                                       
runtime.throw({0x127e3e1?, 0x0?})
        /usr/lib/golang/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
        /usr/lib/golang/src/runtime/signal_unix.go:802 +0x3a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xf074a0, 0xc00069f428)
        /usr/lib/golang/src/runtime/cgocall.go:157 +0x5c fp=0xc00069f400 sp=0xc00069f3c8 pc=0x4059dc
os/user._Cfunc_mygetpwuid_r(0x3e8, 0xc0005a6d50, 0x3bdbc20, 0x400, 0xc000010278)
        _cgo_gotypes.go:175 +0x4c fp=0xc00069f428 sp=0xc00069f400 pc=0x72bc8c
os/user.lookupUnixUid.func1.1(0x3e8, 0x1c06480?, 0xc00069f4c0?, 0x40f927?)
        /usr/lib/golang/src/os/user/cgo_lookup_unix.go:102 +0xa6 fp=0xc00069f488 sp=0xc00069f428 pc=0x72c966
os/user.lookupUnixUid.func1()
        /usr/lib/golang/src/os/user/cgo_lookup_unix.go:102 +0x29 fp=0xc00069f4b8 sp=0xc00069f488 pc=0x72c8a9
os/user.retryWithBuffer(0xc0004bd830, 0xc00069f598)
        /usr/lib/golang/src/os/user/cgo_lookup_unix.go:244 +0x39 fp=0xc00069f500 sp=0xc00069f4b8 pc=0x72d559
os/user.lookupUnixUid(0x3e8)
        /usr/lib/golang/src/os/user/cgo_lookup_unix.go:95 +0x10f fp=0xc00069f5d8 sp=0xc00069f500 pc=0x72c6af
os/user.current()
        /usr/lib/golang/src/os/user/cgo_lookup_unix.go:48 +0x47 fp=0xc00069f618 sp=0xc00069f5d8 pc=0x72bfc7
os/user.Current.func1()
        /usr/lib/golang/src/os/user/lookup.go:15 +0x17 fp=0xc00069f628 sp=0xc00069f618 pc=0x72b537
sync.(*Once).doSlow(0x1c06480?, 0x1c?)
        /usr/lib/golang/src/sync/once.go:68 +0xc2 fp=0xc00069f688 sp=0xc00069f628 pc=0x4726c2
sync.(*Once).Do(...)
        /usr/lib/golang/src/sync/once.go:59
os/user.Current()
        /usr/lib/golang/src/os/user/lookup.go:15 +0x37 fp=0xc00069f6b8 sp=0xc00069f688 pc=0x72b5d7
os/user.Lookup({0x1246b60, 0x7})
        /usr/lib/golang/src/os/user/lookup.go:33 +0x27 fp=0xc00069f6f8 sp=0xc00069f6b8 pc=0x72b6a7
github.com/containers/storage/pkg/chrootarchive.init.0()
        /home/lsm5/go/src/github.com/containers/podman/vendor/github.com/containers/storage/pkg/chrootarchive/archive.go:23 +0x25 fp=0xc00069f730 sp=0xc00069f6f8 pc=0xa10885
runtime.doInit(0x1bab2e0)
        /usr/lib/golang/src/runtime/proc.go:6222 +0x126 fp=0xc00069f860 sp=0xc00069f730 pc=0x446aa6
runtime.doInit(0x1bac4e0)
        /usr/lib/golang/src/runtime/proc.go:6199 +0x71 fp=0xc00069f990 sp=0xc00069f860 pc=0x4469f1
runtime.doInit(0x1bb08a0)
        /usr/lib/golang/src/runtime/proc.go:6199 +0x71 fp=0xc00069fac0 sp=0xc00069f990 pc=0x4469f1
runtime.doInit(0x1ba9060)
        /usr/lib/golang/src/runtime/proc.go:6199 +0x71 fp=0xc00069fbf0 sp=0xc00069fac0 pc=0x4469f1
runtime.doInit(0x1baa960)
        /usr/lib/golang/src/runtime/proc.go:6199 +0x71 fp=0xc00069fd20 sp=0xc00069fbf0 pc=0x4469f1
runtime.doInit(0x1bad200)
        /usr/lib/golang/src/runtime/proc.go:6199 +0x71 fp=0xc00069fe50 sp=0xc00069fd20 pc=0x4469f1
runtime.doInit(0x1bb1820)
        /usr/lib/golang/src/runtime/proc.go:6199 +0x71 fp=0xc00069ff80 sp=0xc00069fe50 pc=0x4469f1
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:233 +0x1d3 fp=0xc00069ffe0 sp=0xc00069ff80 pc=0x439a53
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00069ffe8 sp=0xc00069ffe0 pc=0x4682a1
```

This is because https://github.com/containers/podman/releases/download/v4.0.2/podman-remote-static.tar.gz is broken and crashes this way.
https://github.com/containers/podman/releases/download/v4.1.0/podman-remote-static.tar.gz is also not good as this is a Windows binary.
https://github.com/containers/podman/releases/download/v4.1.1/podman-remote-static.tar.gz seems better.

**Comment by gbraad** [comment]
@cfergeau perhaps report this upstream. they might have to add a note to their release.

**Comment by cfergeau** [comment]
They are aware of it.

**Comment by cfergeau** [comment]
https://github.com/containers/podman/issues/14353
https://github.com/containers/podman/issues/14201

**Comment by gbraad** [comment]
ah, that is the cause. I have seen this issue

**Comment by praveenkumar** [comment]
Closing this since it is now fixed.
