### ISSUE TITLE
make integration segfault

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#501]
Running make integration on my machine segfaults:
```
    $ make integration
    panic: runtime error: index out of range
    
    goroutine 1 [running]:
    github.com/code-ready/crc/test/integration/crcsuite.ParseFlags()
            /home/teuf/go/src/github.com/code-ready/crc/test/integration/crcsuite/prepare.go:64 +0x154
    github.com/code-ready/crc/test/integration.parseFlags()
            /home/teuf/go/src/github.com/code-ready/crc/test/integration/integration_test.go:62 +0x25
    github.com/code-ready/crc/test/integration.TestMain(0xc0000b1f10)
            /home/teuf/go/src/github.com/code-ready/crc/test/integration/integration_test.go:33 +0x34
    main.main()
            _testmain.go:38 +0x10f
    FAIL    github.com/code-ready/crc/test/integration      0.015s
    make: *** [Makefile:120: integration] Error 1
```

This happens because I did not set BUNDLE_LOCATION and PULL_SECRET_PATH.

**Comment by gbraad** [comment]
seems it does not check if the recieved arguments are populated. it should bailout when not provided.
