### ISSUE TITLE
[BUG] Fatal Error: runtime: out of memory

### ISSUE THREAD

**Issue by odockal** [code-ready/crc#677]
### General information
I have 4 CPU 8GB rhel VM machine and I got out of memory when unpacking the bundle from crc binary. This is happening when `crc setup`.

  * OS: Linux
  * Hypervisor: KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes

## CRC version
```
version: 1.0.0-rc.0+34371d3
OpenShift version: 4.2.0-0.nightly-2019-09-26-192831 (embedded in binary)
```
  
## CRC status
```
ERRO Error occurred: Machine "crc" does not exist. Use "crc start" to add a new one. 
```

## CRC config
```
```

## Host Operating System
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
```

### Steps to reproduce

  1. RHEL VM with 4 CPU and 8 GB ram. 
  2. crc setup
  3. 
  4. 

### Expected
Setup went alright

### Actual
Out of memory error

### Logs
```
[hudson@rhel7-x64-jbds-odockal crc-linux-1.0.0-rc.0-amd64]$ ./crc setup
INFO Checking if running as non-root              
INFO Caching oc binary                            
INFO Setting up virtualization                    
INFO Setting up KVM                               
INFO Installing libvirt service and dependencies  
INFO Adding user to libvirt group                 
INFO Enabling libvirt                             
INFO Starting libvirt service                     
INFO Checking if a supported libvirt version is installed 
INFO Installing crc-driver-libvirt                
INFO Removing older system-wide crc-driver-libvirt 
INFO Setting up libvirt 'crc' network             
INFO Starting libvirt 'crc' network               
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Writing Network Manager config for crc       
INFO Will use root access: write NetworkManager config in /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf 
INFO Will use root access: execute systemctl daemon-reload command 
INFO Will use root access: execute systemctl stop/start command 
INFO Writing dnsmasq config for crc               
INFO Will use root access: write dnsmasq configuration in /etc/NetworkManager/dnsmasq.d/crc.conf 
INFO Will use root access: execute systemctl daemon-reload command 
INFO Will use root access: execute systemctl stop/start command 
INFO Unpacking bundle from the CRC binary         
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xa1e775, 0x16)
	/usr/lib/golang/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc104000000, 0x100000000, 0xec3678)
	/usr/lib/golang/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0xea9b80, 0x100000000, 0x0, 0x4590b0)
	/usr/lib/golang/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0xea9b80, 0x80000, 0x0)
	/usr/lib/golang/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0xea9b80, 0x80000, 0xec3688, 0x0)
	/usr/lib/golang/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0xea9b80, 0x80000, 0xffffffffffff0101, 0x7f63491c7dd8)
	/usr/lib/golang/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/lib/golang/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0xea9b80, 0x80000, 0x7f6349010101, 0x43968f)
	/usr/lib/golang/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0xfffffe00, 0xc000030101, 0xc000000300)
	/usr/lib/golang/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
	/usr/lib/golang/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
	/usr/lib/golang/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/lib/golang/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/lib/golang/src/runtime/asm_amd64.s:311 fp=0xc0005e37d8 sp=0xc0005e37d0 pc=0x45af20
runtime.mallocgc(0xfffffe00, 0x94c480, 0x1, 0xc0005e38b0)
	/usr/lib/golang/src/runtime/malloc.go:913 +0x896 fp=0xc0005e3878 sp=0xc0005e37d8 pc=0x4119d6
runtime.makeslice(0x94c480, 0xfffffe00, 0xfffffe00, 0x40000000, 0x40000000, 0x0)
	/usr/lib/golang/src/runtime/slice.go:70 +0x77 fp=0xc0005e38a8 sp=0xc0005e3878 pc=0x446117
bytes.makeSlice(0xfffffe00, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/bytes/buffer.go:231 +0x6d fp=0xc0005e38e8 sp=0xc0005e38a8 pc=0x4edc1d
bytes.(*Buffer).grow(0xc0000ab9d0, 0x200, 0x40000000)
	/usr/lib/golang/src/bytes/buffer.go:144 +0x16c fp=0xc0005e3938 sp=0xc0005e38e8 pc=0x4ed57c
bytes.(*Buffer).ReadFrom(0xc0000ab9d0, 0xab6340, 0xc00015be60, 0xc0001a23c0, 0xc0000d97e8, 0x0)
	/usr/lib/golang/src/bytes/buffer.go:204 +0x4b fp=0xc0005e39a8 sp=0xc0005e3938 pc=0x4eda0b
io/ioutil.readAll(0xab6340, 0xc00015be60, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/io/ioutil/ioutil.go:36 +0xb5 fp=0xc0005e39f0 sp=0xc0005e39a8 pc=0x535a05
io/ioutil.ReadAll(0xab6340, 0xc00015be60, 0xc00015be60, 0xc00015be60, 0x0, 0x0, 0xc0000d9760)
	/usr/lib/golang/src/io/ioutil/ioutil.go:45 +0x3e fp=0xc0005e3a40 sp=0xc0005e39f0 pc=0x535ace
github.com/YourFin/binappend.(*Extractor).ByteArray(0xc00015bce0, 0xc000404b80, 0x3e, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/prkumar/go/pkg/mod/github.com/!your!fin/binappend@v0.0.0-20181105185800-0add4bf0b9ad/reading.go:183 +0xd3 fp=0xc0005e3ab8 sp=0xc0005e3a40 pc=0x8e5833
github.com/code-ready/crc/pkg/crc/preflight.fixBundleCached(0xc0005e1c00, 0x0, 0x0)
	/var/lib/jenkins/workspace/crc_release/pkg/crc/preflight/preflight_checks_common.go:42 +0x12f fp=0xc0005e3b70 sp=0xc0005e3ab8 pc=0x8e673f
github.com/code-ready/crc/pkg/crc/preflight.preflightCheckAndFix(0xa20200, 0xa3f8c8, 0xa3f950, 0xa29146, 0x24, 0x0)
	/var/lib/jenkins/workspace/crc_release/pkg/crc/preflight/preflight.go:42 +0x17b fp=0xc0005e3c38 sp=0xc0005e3b70 pc=0x8e635b
github.com/code-ready/crc/pkg/crc/preflight.SetupHost(0xa15037, 0x7)
	/var/lib/jenkins/workspace/crc_release/pkg/crc/preflight/preflight_linux.go:196 +0x88e fp=0xc0005e3c80 sp=0xc0005e3c38 pc=0x8ed8fe
github.com/code-ready/crc/cmd/crc/cmd.runSetup(0xec14a8, 0x0, 0x0)
	/var/lib/jenkins/workspace/crc_release/cmd/crc/cmd/setup.go:35 +0x4d fp=0xc0005e3cc8 sp=0xc0005e3c80 pc=0x8efe2d
github.com/code-ready/crc/cmd/crc/cmd.glob..func9(0xe99460, 0xec14a8, 0x0, 0x0)
	/var/lib/jenkins/workspace/crc_release/cmd/crc/cmd/setup.go:27 +0x3f fp=0xc0005e3cf0 sp=0xc0005e3cc8 pc=0x8f222f
github.com/spf13/cobra.(*Command).execute(0xe99460, 0xec14a8, 0x0, 0x0, 0xe99460, 0xec14a8)
	/home/prkumar/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc fp=0xc0005e3de0 sp=0xc0005e3cf0 pc=0x82978c
github.com/spf13/cobra.(*Command).ExecuteC(0xe99200, 0x14, 0x0, 0x0)
	/home/prkumar/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd fp=0xc0005e3f20 sp=0xc0005e3de0 pc=0x82a32d
github.com/spf13/cobra.(*Command).Execute(0xe99200, 0xe99de0, 0xc0000cbf78)
	/home/prkumar/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b fp=0xc0005e3f50 sp=0xc0005e3f20 pc=0x82a00b
github.com/code-ready/crc/cmd/crc/cmd.Execute()
	/var/lib/jenkins/workspace/crc_release/cmd/crc/cmd/root.go:67 +0x2d fp=0xc0005e3f88 sp=0xc0005e3f50 pc=0x8efb9d
main.main()
	/var/lib/jenkins/workspace/crc_release/cmd/crc/main.go:10 +0x25 fp=0xc0005e3f98 sp=0xc0005e3f88 pc=0x8f2c15
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:201 +0x207 fp=0xc0005e3fe0 sp=0xc0005e3f98 pc=0x431ed7
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0005e3fe8 sp=0xc0005e3fe0 pc=0x45d001

goroutine 46 [select]:
net/http.(*persistConn).writeLoop(0xc0005d0360)
	/usr/lib/golang/src/net/http/transport.go:1887 +0x113
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1341 +0x966

goroutine 45 [IO wait]:
internal/poll.runtime_pollWait(0x7f63500bee30, 0x72, 0xc0005df858)
	/usr/lib/golang/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000174318, 0x72, 0xffffffffffffff00, 0xab7820, 0xe595d8)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000174318, 0xc00022c000, 0x1000, 0x1000)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000174300, 0xc00022c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000174300, 0xc00022c000, 0x1000, 0x1000, 0x40e3bb, 0xc000010000, 0x986400)
	/usr/lib/golang/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000160060, 0xc00022c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc000452720, 0xab67e0, 0xc000160060, 0x5, 0xc000160060, 0x30)
	/usr/lib/golang/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc000480380, 0xa40717, 0xc0004804a0, 0x459ef0)
	/usr/lib/golang/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc000480380, 0xc0005e5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:1145 +0xf1
net/http.(*persistConn).Read(0xc0005d0360, 0xc0005e5000, 0x1000, 0x1000, 0xc0005dfc70, 0x40a935, 0xc000086900)
	/usr/lib/golang/src/net/http/transport.go:1499 +0x75
bufio.(*Reader).fill(0xc0001589c0)
	/usr/lib/golang/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc0001589c0, 0x1, 0x0, 0x0, 0x1, 0xc000226360, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:132 +0x3f
net/http.(*persistConn).readLoop(0xc0005d0360)
	/usr/lib/golang/src/net/http/transport.go:1647 +0x1a2
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1340 +0x941

goroutine 49 [select]:
net/http.(*persistConn).writeLoop(0xc0000e2120)
	/usr/lib/golang/src/net/http/transport.go:1887 +0x113
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1341 +0x966

goroutine 48 [IO wait]:
internal/poll.runtime_pollWait(0x7f63500bec90, 0x72, 0xc000056858)
	/usr/lib/golang/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc0000ac218, 0x72, 0xffffffffffffff00, 0xab7820, 0xe595d8)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc0000ac218, 0xc0000b0000, 0x8000, 0x8000)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc0000ac200, 0xc0000b0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc0000ac200, 0xc0000b0000, 0x8000, 0x8000, 0x40e3bb, 0xc000010000, 0x986400)
	/usr/lib/golang/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000160078, 0xc0000b0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:177 +0x68
crypto/tls.(*block).readFromUntil(0xc000453260, 0xab67e0, 0xc000160078, 0x5, 0xc000160078, 0x30)
	/usr/lib/golang/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc000480a80, 0xa40717, 0xc000480ba0, 0x459ef0)
	/usr/lib/golang/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc000480a80, 0xc00013a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:1145 +0xf1
net/http.(*persistConn).Read(0xc0000e2120, 0xc00013a000, 0x1000, 0x1000, 0xc000056c70, 0x40a935, 0xc000086c60)
	/usr/lib/golang/src/net/http/transport.go:1499 +0x75
bufio.(*Reader).fill(0xc000158f00)
	/usr/lib/golang/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc000158f00, 0x1, 0x0, 0x0, 0x1, 0xc000086d20, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:132 +0x3f
net/http.(*persistConn).readLoop(0xc0000e2120)
	/usr/lib/golang/src/net/http/transport.go:1647 +0x1a2
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1340 +0x941
```

You can start crc with `crc start --log-level debug` to collect logs.
Please consider posting this on http://gist.github.com/ and post the link in the issue.

**Comment by praveenkumar** [comment]
@odockal was it a fresh VM and no other workload running on that system. We will try to find out how much memory unpack required.

**Comment by odockal** [comment]
@praveenkumar  Yes, fresh machine and no substantial program eating resources. I would not expect this machine to run crc like a charm, I am just concerned about unpack draining all the memory. 

Thanks for looking to this.

**Comment by anjannath** [comment]
@odockal How much RAM in the machine?

**Comment by cfergeau** [comment]
I wrote https://github.com/cfergeau/crc/commit/266ab267d9b7 a while back, and this could help with memory consumption during bundle unpacking. I haven't tried to get it upstream yet though ;)

**Comment by cfergeau** [comment]
> @odockal What is the size of RAM in the machine?

The VM has 8GB

**Comment by odockal** [comment]
> > @odockal What is the size of RAM in the machine?
> 
> The VM has 8GB

That's right, it is in the issue template.

**Comment by cfergeau** [comment]
I've filed https://github.com/code-ready/crc/pull/789

**Comment by robinsonap** [comment]
Help

**Comment by cfergeau** [comment]
The VM CodeReady Containers will create requires more than 9GB of RAM, so I am afraid this is not going to work on a host system with only 8GB RAM total.
